### ISSUE TITLE
Organization type not sufficient for Department property

### ISSUE THREAD

**Issue by halovanic** [RehanSaeed/Schema.NET#13]
The Department Property in `OrganizationAndPlace` is of type `Organization` only.  This makes it impossible to set Department to any other `OrganizationAndPlace`, such as the `LocalBusiness` types.

Place in particular is necessary to set OpeningHoursSpecification:
https://developers.google.com/search/docs/data-types/local-business#multiple_departments

Thanks,
Alex

**Comment by RehanSaeed** [comment]
Right now this is a limitation of this library. There are a few types which are combinations of other types like `OrganizationAndPlace`. Wherever there is a property of type `Organization` or `Place` you cannot use the `OrganizationAndPlace` type because `OrganizationAndPlace` inherits from `Organization`.

The only way to solve this issue that I can think of is to split dual types like `OrganizationAndPlace` into two types:

- `OrganizationThenPlace` inherits from `Organization`.
- `PlaceThenOrganization` inherits from `Place`.

Note that there are also some types that are made of a combination of more than two types. I'd be willing to accept a PR for this work.

**Comment by RehanSaeed** [comment]
Thats a decent idea.

I don't know how much you know about Schema.NET but I've written a console app to generate C# classes from the Schema.org API. We'd want to change the tool to output interfaces as well as classes and then change all properties to use the interfaces instead.

**Comment by halovanic** [comment]
OK, I will try to learn that tool and see if I can put something together.

**Comment by hades200082** [comment]
Any movement on this? I'm having this same issue trying to set Department in Organization but cannot set opening hours.

**Comment by RehanSaeed** [comment]
No movement.

**Comment by hades200082** [comment]
What's blocking the PR at the moment?

**Comment by RehanSaeed** [comment]
Me! I haven't had time to look at the PR in depth. Also I requested some tests but those have not been added. Maybe I'll just merge the PR and add some tests myself.

**Comment by hades200082** [comment]
Ok, fair enough. Was wondering if it was something that needed fixing first and would've jumped in to take a look but if it's just waiting on you reviewing I'll just sit patiently.

**Comment by RehanSaeed** [comment]
If you'd like to help. Please feel free to add some tests showing usage that fixes the above problem and the PR now needs to be rebased too.

**Comment by RehanSaeed** [comment]
This is now fixed. You should see a big release soon.
