### ISSUE TITLE
BreadcrumbList itemListElement listitem with string item value

### ISSUE THREAD

**Issue by throwaway20210** [RehanSaeed/Schema.NET#257]
Is it possible to produce JSON like this using this library ? 

```    {
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      "itemListElement": [{
        "@type": "ListItem",
        "position": 1,
        "name": "Books",
        "item": "https://example.com/books"
      },{
        "@type": "ListItem",
        "position": 2,
        "name": "Science Fiction",
        "item": "https://example.com/books/sciencefiction"
      },{
        "@type": "ListItem",
        "position": 3,
        "name": "Award Winners"
      }]
    }
```

I tried but I get a compiler error when assigning a string to `item`

**Comment by RehanSaeed** [comment]
See this unit test for an example:

https://www.github.com/RehanSaeed/Schema.NET/tree/main/Tests%2FSchema.NET.Test%2Fcore%2FBreadcrumbListTest.cs

**Comment by throwaway20210** [comment]
No, I need `itemListElement.*.item` to be a string, not an object, that unit test does not show that.

**Comment by Turnerj** [comment]
Hey @throwaway20210 , unfortunately Schema.org has the property `item` on `ListItem` as `Thing`, meaning it can only be an object. See: https://schema.org/ListItem

Using the example for JSON-LD on Schema.org for [BreadcrumbList](https://schema.org/BreadcrumbList), the way you could implement what you want with objects would be similar to the following:

```json
{
	"@context": "https://schema.org",
	"@type": "BreadcrumbList",
	"itemListElement": [{
		"@type": "ListItem",
		"position": 1,
		"item": {
			"@type": "Thing",
			"name": "Books",
			"url": "https://example.com/books"
		}
	},{
		"@type": "ListItem",
		"position": 2,
		"item": {
			"@type": "Thing",
			"name": "Science Fiction",
			"url": "https://example.com/books/sciencefiction"
		}
	},{
		"@type": "ListItem",
		"position": 3,
		"item": {
			"@type": "Thing",
			"name": "Award Winners",
			"url": "https://example.com/books/sciencefiction/awardwinners"
		}
	}]
}
```

You shouldn't have a problem achieving the above through Schema.NET. In theory, you could use the name and URL properties on `ListItem` directly but it really depends on the receiving side of the Schema.org data to whether they would understand that.

Alternatively to using type "Thing" for the items, you could specify "WebPage" instead as they are all web pages.

As an aside, breadcrumbs is actually a kinda weird schema representation. As a concept, they only exist with web pages so you would think a restriction to an item list that only has web pages would make sense. Yet because of using the shared `ListItem` type, no such restriction can exist so the item types could be any schema type at all.

**Comment by AlizerUncaged** [comment]
I'd like to point out that isn't that case for Google, Google uses `item` rather than URL https://developers.google.com/search/docs/appearance/structured-data/breadcrumb and I've checked on my webmaster page that using `url` renders the BreadcrumbList invalid

**Comment by Turnerj** [comment]
@AlizerUncaged What you see with Google taking a Url or a Thing is Google deviating from the schema.org standard which is where we generate our entire model from - if you want to complain to anyone, its either the people who wrote the standard or Google for not following it. The screenshot you got of their docs does say you can use a Thing with the `@id` property set to the URL you want. You should be able to do that today with Schema.NET
