### ISSUE TITLE
OneOrMany ctor to accept null?

### ISSUE THREAD

**Issue by benmccallum** [RehanSaeed/Schema.NET#29]
Just ran into a situation where I'm passing in `null` into a property that's `OneOrMany<T>` and the ctor(T item) throws an exception. 

Just wondering whether this is necessary or we can allow null to be set and handled internally. Otherwise code like below becomes much more complicated as I need to null-check every assignment and can't use object initialization, instead need to instantiate then assign properties if not null.

```
            return new LocalBusiness
            {
                Name = Name,
                Image = Image,
                PriceRange = "$$",
                Address = new PostalAddress
                {
                    StreetAddress = Address,
                    AddressLocality = Suburb,
                    AddressRegion = State?.ToUpper(),
                    PostalCode = Postcode
                }
            };
```

What do you think? Would it be possible given all the generics/internals in play here?

As is the behaviour for other properties that allow `null`, I'd expect if `OneOrMany<T>` was set to null to not render out to JSON. Or I guess respect the `JsonSerializerSettings` null handling we now have an overload for. Assuming the value returned is null that should all work ootb.

**Comment by benmccallum** [comment]
I feel like this null check and throw might be new. Suprised I didn't get it originally.

**Comment by benmccallum** [comment]
Nope, checked git blame and commit is from Feb. Hmm, probably a few pages broken on my site then ha!

**Comment by RehanSaeed** [comment]
I'm assuming you mean that we just remove the null check at https://github.com/RehanSaeed/Schema.NET/blob/09b2616a253d329c24134da9d5d68ae69a742176/Source/Schema.NET/OneOrMany%7BT%7D.cs#L23-L26

I.....guess thats ok. Not sure if there would be any unintended consequences of this.

**Comment by benmccallum** [comment]
Yea that's the one. It's super tedious to handle nulls as it is right now. I can maybe give it a go removing it and seeing what happens if you're open to the idea?

**Comment by RehanSaeed** [comment]
Please do.

**Comment by tompazourek** [comment]
I had the same issue, the site broke when I updated to the latest version.

I resolved it temporarily by appending ` ?? new OneOrMany<string>?()`, e. g.:

```
return new LocalBusiness
{
    Name = Name,
    Image = Image,
    PriceRange = "$$",
    Address = new PostalAddress
    {
        StreetAddress = Address,
        AddressLocality = Suburb,
        AddressRegion = State?.ToUpper() ?? new OneOrMany<string>?(),
        PostalCode = Postcode
    }
};
```

It's pretty ugly, but fixes the issue.

**Comment by benmccallum** [comment]
I knew it must've been the latest release that introduced this, good to see somehow else confirm.

Ahh, didn't think of that, that's a better workaround than what I was doing. I've been pretty busy lately but hopefully will get a chance  to remove that check and see what happens.

**Comment by nickevansuk** [comment]
Thanks @tompazourek, that was super helpful getting us out of a tight spot with a deadline!

@benmccallum @RehanSaeed turns out removing that null check creates a few issues when ignoring nulls on serialisation (as the value is not actually null, it's a null within a struct that returns null via `IValue`, which means we're forced to rely on `ValuesConverter` calling `writer.WriteNull()` which ignores `NullValueHandling.Ignore`). It looks like it might be better to keep the null check in and solve this issue in the implicit conversion operators to stop the null-valued `IValue`s being created in the first place. This would require switching from structs to classes though...

See full details in PR https://github.com/RehanSaeed/Schema.NET/pull/36 - look forward to your thoughts!

**Comment by RehanSaeed** [comment]
@nickevansuk First of all, thanks for the PR and it's cool that you are finding this library useful 👍 .

- Nulls must be ignored
- Empty arrays must be ignored
- Strings that are empty or contain whitespace must be ignored.

These are interesting requirements and I can see why they might be useful. Can some of this be handled by the toggles in JSON.NET's `JsonSerializerSettings` and other JSON.NET [extensibility points](https://stackoverflow.com/questions/11320968/can-newtonsoft-json-net-skip-serializing-empty-lists) I found after a cursory look?

Switching from `struct` to `class` is a bit of a downer. The ideal solution would not make this trade-off. You won't see any performance impact. Allocating memory on the heap is cheap. The performance impact comes when the garbage collector runs in this case.

I'm on holiday at the moment before I start a new job so have not had much time to look at this and see if there is a way to do all of the above without using `class`. If anyone gets there first, great otherwise I'll take a look when I get a chance.

**Comment by nickevansuk** [comment]
Hi @RehanSaeed thanks so much for your quick response on this! We had to ship something for production last week so rather than trying to push for this fix to be accelerated we've temporarily forked this project for NuGet so that we can ship OpenActive.NET with solid dependencies.


https://github.com/openactive/OpenActive.NET/blob/0e68ea1ead411259a948acec6aee5fd45fad8911/OpenActive.NET/OpenActiveSerializer.cs#L179

**Comment by nickevansuk** [comment]
Hi @RehanSaeed thanks so much for your quick response on this (and congrats on your new job!)! We had to ship something to production last week that required OpenActive.NET to be stable, so rather than trying to push for this fix to be accelerated (especially while you're on holiday!) we've temporarily [forked](https://www.nuget.org/packages/Schema.NET.NullHandling/) this project for NuGet so that we could ship OpenActive.NET with solid dependencies. We're keen to kill the fork and revert to use Schema.NET as soon as we can though of course.

I can totally see that switching to `class` has some downsides, though again it would be interesting to understand the garbage collector performance impact too, and at what size of object it becomes significant - OA.NET generally deals in pages of 500 schema.org `Thing`s, which is probably much large than most uses of Schema.NET. As all of [OpenActive](https://www.openactive.io/) is open data you can actually see an example output [here](https://opendata.leisurecloud.live/api/feeds/fusion-lifestyle-live-session-series) linked from [here](https://fusionopendata.fusion-lifestyle.com/OpenActive/). I guess one comment would be that the type classes are on the heap anyway, so GC is already cleaning these up...

I did spend some time looking at other options but as mentioned above the problem with using a nullable `struct` is that it doesn't seem to be possible to return null in the implicit conversion operators? So here are the routes I tried and got to dead ends on:
1. Return null for nullable `struct` implicit conversion operators, so that `NullValueHandling.Ignore` works
2. Use `DefaultValueHandling.Ignore` and see if it recognises nullable `structs` that are set to `default`
3. Write a custom version of `writer.WriteNull()` in the `ValuesConverter` that respects `NullValueHandling.Ignore` (this looked possible but quite messy, so if we can write something messy but well-tested here it might be a way of avoiding `class`es - though the maintenance of this should probably be traded off against the performance impact of classes on the heap here).

The thing that swayed me towards classes with more robust implicit conversion operators as a route was also your other point about JSON.NET extensibility points - yes there's a relevant extension via `ShouldSerialize` (which we actually [already use](https://github.com/openactive/OpenActive.NET/blob/0e68ea1ead411259a948acec6aee5fd45fad8911/OpenActive.NET/OpenActiveSerializer.cs#L179) in OA.NET for simple properties). The challenge with this one is that it requires reflection and I couldn't seem to find (after much Googling) a robust way of selecting the object's own properties (rather than its parents) if the property is overridden - which means the implementation currently in OA.NET will fail in some edge cases. As you can see from the commented out code in the link above there are also challenges using this to detect every generic type of Schema.NET that could represent a string - which is why it seemed cleaner to do it consistently in the implicit conversion operators.

Look forward to your thoughts!

**Comment by RehanSaeed** [comment]
The net major version has had some fairly big changes which may affect this. Please take a look.

**Comment by nickevansuk** [comment]
Looks good @RehanSaeed, though it doesn't seem to fix this particular issue. Need to fix the implicit operators to fix this.

Do let me know your thoughts on #issuecomment-473652862 so we can proceed

**Comment by RehanSaeed** [comment]
Removing the null check in my mixed-types branch I mention above seems to have no adverse affects. Tests all pass. Please give it a go.

**Comment by nickevansuk** [comment]
@RehanSaeed I've pulled over the enhanced test from the [fix PR](https://github.com/RehanSaeed/Schema.NET/pull/36) into a [new PR](https://github.com/RehanSaeed/Schema.NET/pull/50) based off your new branch.

If you run that enhanced test you'll see it fails, so seems the issue that we're discussing here still exists.

**Comment by RehanSaeed** [comment]
Merged the test. Will take a look.

**Comment by RehanSaeed** [comment]
Ok I took a look and [this](https://github.com/RehanSaeed/Schema.NET/blob/0c3081bec6c661d2a5a7431086972e24541647ae/Source/Schema.NET/ValuesConverter.cs#L192) is the line at fault. We are writing a null for a property even though we have set `NullValueHandling.Ignore`. I think this is because this type is a `Nullable<T>` enumeration. Apparently `NullValueHandling` only affects classes and not structs.

I spent some time debugging it but this is where my JSON.NET knowledge is falling over. Would appreciate some help looking at the code I mentioned. Will take another look tomorrow. I found a [StackOverflow question](https://stackoverflow.com/questions/33241039/nullvaluehandling-ignore-with-jsonconverterwritejson) which is very similar.

**Comment by nickevansuk** [comment]
Hi @RehanSaeed I agree with your analysis - that's why the [PR](https://github.com/RehanSaeed/Schema.NET/pull/36) switches to classes from structs.

I found the same StackOverflow question (and in fact linked it in paragraph 9 of https://github.com/RehanSaeed/Schema.NET/pull/36), and concluded it was messy, but possible. Other options are outlined in the [comment above](https://github.com/RehanSaeed/Schema.NET/issues/29#issuecomment-473652862).

Sorry if my prose wasn't clear, if you reread both the [PR](https://github.com/RehanSaeed/Schema.NET/pull/36) and [comment above](https://github.com/RehanSaeed/Schema.NET/issues/29#issuecomment-473652862) you'll see I've outlined a few options for ways forward here - specifically because of the [line](https://github.com/RehanSaeed/Schema.NET/blob/0c3081bec6c661d2a5a7431086972e24541647ae/Source/Schema.NET/ValuesConverter.cs#L192) you've referenced.

Welcome your thoughts on these.

**Comment by RehanSaeed** [comment]
Apologies, I was working on another PR/issue and thought I could get this for free or with little effort. Let me investigate.

**Comment by RehanSaeed** [comment]
I've written a minimal repro and posted it on StackOverflow [here](https://stackoverflow.com/questions/56261012/how-to-serialize-using-json-net-and-ignore-a-nullable-struct-value) while I complete the rest of the work on mixed types, I'm hoping someone clever will solve the problem as I haven't been able to (without having to do some pretty nasty things as you suggest). It seems like this should be easy and I'm missing something obvious. I'll revisit this in a few days which I expect might mean merging your PR to switch to classes.

**Comment by nickevansuk** [comment]
Thanks @RehanSaeed, the answer so far looks interesting - lots of tradeoffs to consider. Look forward to the update on what you decide.

**Comment by RehanSaeed** [comment]
That StackOverflow answer was great. I went with option 2 that he provided. It allows you do do this which fixes this issue:

```
int foo = null;
new SchemaDotnetType()
{
    Foo = foo
};
```

However, the downside is that you can no longer do this as it becomes a compile time error:

```
new SchemaDotnetType()
{
    Foo = null
};
```

However, I think it's really weird to explicitly set a property to null like this, so I'm ok with it. If you really really want to explicitly set a property to null, you can still do it like this:

```
new SchemaDotnetType()
{
    Foo = (int)null
};
```

Or like this:


```
new SchemaDotnetType()
{
    Foo = new OneOrMany<int>((int)null)
};
```

Thoughts?

**Comment by nickevansuk** [comment]
Nice! Agree, seems like the best of both worlds! And we get to keep the structs too :)

Do you have any ideas of how we can fulfil our additional requirement of "Strings that are empty or contain only whitespace must be ignored" using this?

**Comment by RehanSaeed** [comment]
Hmmmmmm.

I suppose this could be implemented in `ValuesJsonConverter.WriteJson`. We could check for a collection of strings and treat that as a special case by running `.Where(x => !string.IsNullEmptyOrWhitespace(x))` on it.

Can an empty or white space string be valid? I'm not certain this is a good thing to do.

**Comment by nickevansuk** [comment]
Yep, there are no cases in schema.org markup where empty or white space strings are valid - they are simply a verbose equivalent of ignoring the property.

As you can see from e.g https://search.google.com/structured-data/testing-tool?utm_campaign=devsite&utm_medium=jsonld&utm_source=article if you try editing the `name` property, the values of `null`, `""` and `"   "` are all treated the same.

**Comment by RehanSaeed** [comment]
Ok, sounds like we should implement this feature then. Do you think we should ignore empty/whitespace in the `JsonConverter` or in `OneOrMany<T>`? I'm leaning towards the former.

**Comment by RehanSaeed** [comment]
I tried to quickly implement this but I think it will take some more time or maybe my brain is tired. I want to get what I have in and I'll take a PR for the whitespace or empty string issue. Anyway here is a unit test to add when this works:

```
        [Theory]
        [InlineData("")]
        [InlineData(" ")]
        [InlineData("  ")]
        public void ToString_EmptyOrWhiteSpace_OmitsNameProperty(string name)
        {
            var book = new Book() { Name = name };
            Assert.Equal("{\"@context\":\"http://schema.org\",\"@type\":\"Book\"}", book.ToString());
        }
```

**Comment by nickevansuk** [comment]
Agree with your approach to use `OneOrMany<T>`. I've created a PR as you requested .

Unfortunately additional tests for `Values<>` have revealed that this issue is only fixed for properties that use `OneOrMany<>` and not for properties that use `Values<>`. See the PR tests for more details.

**Comment by benmccallum** [comment]
Awesome work on this guys! Appreciate the effort you've both put in. Will make using this a lot easier when dealing with nulls :) is it released yet Rehan?

**Comment by RehanSaeed** [comment]
4.0.0 was released. FYI, you can watch for releases on GitHub projects (new'ish feature).
